title: Riki Mardiyanto
description: Wellcome to My Page

url: http://rikimardy.github.com/rikimardy
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Tentang
   url: /about
 - title: Kontak
   url: /contact

social:
   github: rikimardy
   twitter: @rikimardiyanto
   facebook: Ricky Ackerman
   email: caritoblog802s@gmail.com

google_analytics: "UA-58263416-1"
